### ISSUE TITLE
Missing algos

### ISSUE THREAD

**Issue by finmine** [saltpool/yiimp#6] opened 2024-11-19 15:34 UTC
Hello,

I think this repo is forked from https://github.com/afiniel/yiimp ?

Still here is missing algos like Mike, MinotaurX, Memehash etc.

Can you please add those algos before I use installer?

Thank you!

**Comment by saltpool** [comment] 2024-11-19 22:57
How github works is that if you have a request for features, you create a pull request and add changes in there so that they are ready for review. Once reviewed and confirmed, they get merged to the main branch for release.  If you want these algos added, please create a pull request and populate the changes you want made and they will then be reviewed.  This is a community project.

Closing this since it is not an issue but a request for enhancement. Looking forward to seeing a pull request.

**Closed as completed by saltpool** 2024-11-19 22:57 UTC
